# 数据生成

该文本用于生成NN的一些测试数据，主要是python能够更方便生成重复数据

In [2]:
import numpy as np

## pooling

In [2]:
in_vec = [-1, 0, 1, 2, 2, 3, 5, 4, 7, 0, 0, 0, -1, -2, 0, 9]
in_vec = np.tile(in_vec, (2,1))
in_vec

array([[-1,  0,  1,  2,  2,  3,  5,  4,  7,  0,  0,  0, -1, -2,  0,  9],
       [-1,  0,  1,  2,  2,  3,  5,  4,  7,  0,  0,  0, -1, -2,  0,  9]])

In [3]:
in_vec = [-1, 0, 1, 2, 2, 3, 5, 4, 7, 0, 0, 0, -1, -2, 0, 9]
in_vec = np.repeat(in_vec, 2)
in_vec

array([-1, -1,  0,  0,  1,  1,  2,  2,  2,  2,  3,  3,  5,  5,  4,  4,  7,
        7,  0,  0,  0,  0,  0,  0, -1, -1, -2, -2,  0,  0,  9,  9])

## Conv

### 例1

In [22]:
in_vec_channel_1 = np.ones((16,), dtype=np.int32)
in_vec_channel_2 = in_vec_channel_1 * 2

print(in_vec_channel_1)
print(in_vec_channel_2)

# in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).reshape(-1)
in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).T.reshape(-1)
in_vec

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 2], dtype=int32)

In [23]:
weight_kernel_1_channel_1 = np.ones((3, 3), dtype=np.int32) * 2
weight_kernel_1_channel_2 = np.ones((3, 3), dtype=np.int32) * 3
weight_kernel_1 = np.array([weight_kernel_1_channel_1, weight_kernel_1_channel_2])
print(weight_kernel_1.shape)

weight_kernel_2_channel_1 = np.ones((3, 3), dtype=np.int32) * 3
weight_kernel_2_channel_2 = np.ones((3, 3), dtype=np.int32) * 1
weight_kernel_2 = np.array([weight_kernel_2_channel_1, weight_kernel_2_channel_2])
print(weight_kernel_2.shape)

weight = np.array([weight_kernel_1, weight_kernel_2]).transpose(1,2,3,0)
print(weight.shape)
weight = weight.reshape(-1)

# 生成所有权重相同的测试用
# weight = np.ones((36,), dtype=np.int)
weight

(2, 3, 3)
(2, 3, 3)
(2, 3, 3, 2)


array([2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1], dtype=int32)

### 例2

In [50]:
in_vec_channel_1 = np.concatenate((np.arange(1, 10, dtype=np.int32), np.arange(1, 8, dtype=np.int32)))
in_vec_channel_2 = np.ones((16,), dtype=np.int32)

print(in_vec_channel_1)
print(in_vec_channel_2)

# in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).reshape(-1)
in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).T.reshape(-1)
in_vec

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


array([1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9, 1, 1, 1, 2, 1,
       3, 1, 4, 1, 5, 1, 6, 1, 7, 1], dtype=int32)

In [62]:
weight_kernel_1_channel_1 = np.ones((3, 3), dtype=np.int32) * 2
weight_kernel_1_channel_2 = np.arange(1, 10, dtype=np.int32).reshape(3, 3) * -1
weight_kernel_1 = np.array([weight_kernel_1_channel_1, weight_kernel_1_channel_2])
weight_kernel_1 = weight_kernel_1.transpose(1,2,0)
print(weight_kernel_1.shape)

weight_kernel_2_channel_1 = np.array([1,2,3,1,2,3,1,2,3], dtype=np.int32).reshape(3, 3)
weight_kernel_2_channel_2 = np.ones((3, 3), dtype=np.int32)
weight_kernel_2 = np.array([weight_kernel_2_channel_1, weight_kernel_2_channel_2])
weight_kernel_2 = weight_kernel_2.transpose(1,2,0)
print(weight_kernel_2.shape)

weight = np.array([weight_kernel_1, weight_kernel_2])
print(weight.shape)
weight = weight.reshape(-1)

# 生成所有权重相同的测试用
# weight = np.ones((36,), dtype=np.int)
weight

(3, 3, 2)
(3, 3, 2)
(2, 3, 3, 2)


array([ 2, -1,  2, -2,  2, -3,  2, -4,  2, -5,  2, -6,  2, -7,  2, -8,  2,
       -9,  1,  1,  2,  1,  3,  1,  1,  1,  2,  1,  3,  1,  1,  1,  2,  1,
        3,  1], dtype=int32)

## Dense

In [3]:
in_vec = np.array([[-1, -2, 1, 2, 3], [-1, -2, 0, 2, 3]]).T
weight = np.array([[2, 1, 2, 2, 2], [2, 2, 1, 2, 2], [2, 2, 1, 1, 2]], dtype=np.int32)

print('correct answer')
print(np.matmul(weight, in_vec))

correct answer
[[8 6]
 [5 4]
 [3 2]]


In [74]:
in_vec.T

array([[-1, -2,  1,  2,  3]])

In [4]:
weight.T.reshape(-1)

array([2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2], dtype=int32)

# 正确的参考结果生成

In [1]:
import torch

## Conv

### 例2

In [59]:
# 构建输入
in_vec_channel_1 = np.concatenate((np.arange(1, 10, dtype=np.int32), np.arange(1, 8, dtype=np.int32))).reshape(4,4)
in_vec_channel_2 = np.ones((16,), dtype=np.int32).reshape(4,4)

in_vec = np.array([in_vec_channel_1, in_vec_channel_2])
in_vec = in_vec[np.newaxis, :]
print(in_vec.shape)
in_vec

(1, 2, 4, 4)


array([[[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 1, 2, 3],
         [4, 5, 6, 7]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]], dtype=int32)

In [60]:
# 构建权重
weight_kernel_1_channel_1 = np.ones((3, 3), dtype=np.int32) * 2
weight_kernel_1_channel_2 = np.arange(1, 10, dtype=np.int32).reshape(3, 3) * -1
weight_kernel_1 = np.array([weight_kernel_1_channel_1, weight_kernel_1_channel_2])
print(weight_kernel_1.shape)

weight_kernel_2_channel_1 = np.array([1,2,3,1,2,3,1,2,3], dtype=np.int32).reshape(3, 3)
weight_kernel_2_channel_2 = np.ones((3, 3), dtype=np.int32)
weight_kernel_2 = np.array([weight_kernel_2_channel_1, weight_kernel_2_channel_2])
print(weight_kernel_2.shape)

weight = np.array([weight_kernel_1, weight_kernel_2])
print(weight.shape)

# 生成所有权重相同的测试用
# weight = np.ones((36,), dtype=np.int)
weight

(2, 3, 3)
(2, 3, 3)
(2, 2, 3, 3)


array([[[[ 2,  2,  2],
         [ 2,  2,  2],
         [ 2,  2,  2]],

        [[-1, -2, -3],
         [-4, -5, -6],
         [-7, -8, -9]]],


       [[[ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3]],

        [[ 1,  1,  1],
         [ 1,  1,  1],
         [ 1,  1,  1]]]], dtype=int32)

In [61]:
in_vec = torch.Tensor(in_vec)
weight = torch.Tensor(weight)
output = torch.conv2d(in_vec, weight)

output

tensor([[[[ 27.,  27.],
          [ 45.,  45.]],

         [[ 78.,  87.],
          [ 96., 105.]]]])

# 寻找量化参数

In [17]:
scale_input = 0.04273353889584541
scale_filter = 0.007862006314098835
scale_output = 0.19821195304393768
scale = scale_input * scale_filter / scale_output
print(scale)

multipler = 0
shift = 0
for i in range(31):
    temp = scale * 2**(i + 31)
    if temp < 2**31 - 1:
        multipler = int(temp)
        shift = i
    else:
        break

print(multipler, -shift)

0.0016950105554353221
1863683814 -9


# C数组生成

In [2]:
import numpy as np

## 读取npy权重和偏移并生成

In [46]:
def gen_content(pre_info, data: np.ndarray):
    content = pre_info + '[] = {'
    data = data.reshape(-1)
    for item in data:
        content += str(item) + ', '

    content += '};\n\n'
    return content

In [26]:
save_path = './5_cmsis_mlp/model/weights.h'

config = [
    (
        'const q7_t filter_data_dense_1',
        './5_cmsis_mlp/model/mlp_1_sequential_1_dense_2_MatMul.npy'
    ),
    (
        'const q7_t filter_data_dense_2',
        './5_cmsis_mlp/model/mlp_1_sequential_1_dense_3_MatMul.npy'
    ),
    (
        'const int32_t bias_data_dense_1',
        './5_cmsis_mlp/model/dense_2_bias.npy'
    ),
    (
        'const int32_t bias_data_dense_2',
        './5_cmsis_mlp/model/dense_3_bias.npy'
    )
]

with open(save_path, 'w+') as f:
    content = '#include "arm_nnfunctions.h"\n\n'
    for pre_info, data_path in config:
        content += gen_content(pre_info, np.load(data_path))
    f.write(content)

## 输入c数组生成

In [1]:
# mlp模型参数
input_scale = 0.003921568859368563
input_zero_point = -128

In [3]:
def load_mnist(path):
    '''加载mnist数据
        输入:
            path: mnist.npz的路径
    '''

    with np.load(path, allow_pickle=True) as f:
        x_train, y_train = f['x_train'], f['y_train']
        x_test, y_test = f['x_test'], f['y_test']

        return (x_train, y_train), (x_test, y_test)


In [4]:
(x_train, y_train), (x_test, y_test) = load_mnist('data/mnist/mnist.npz')
x_test = x_test / 255.
# 对输入数据进行量化处理
x_test = x_test / input_scale + input_zero_point

x_test = x_test.round().astype(np.int8)

In [8]:
def gen_content(pre_info, data: np.ndarray):
    content = pre_info + '{'
    data = data.reshape(-1)
    for item in data:
        content += str(item) + ', '

    content += '}\n\n'
    return content

In [9]:
save_path = './5_cmsis_mlp/model/inputs.h'

with open(save_path, 'w+') as f:
    content = gen_content('#define INPUT_DATA ', x_test[0])
    f.write(content)

print(y_test[0])

7


# 数据对比

1. 使用tiny_network生成真实输出
2. 在串口中设置保存到log，捕获stm32的输出

## 加载txt文件并对比结果(单层)

In [19]:
import numpy as np

input_data = np.loadtxt('./5_cmsis_mlp/model/cmp/output_dense_1.txt', dtype=np.int64)
input_data_stm32 = np.loadtxt('./5_cmsis_mlp/model/cmp/output_dense_1_stm32.txt', dtype=np.int64)

weight = np.load('./5_cmsis_mlp/model/mlp_1_sequential_1_dense_3_MatMul.npy')
bias = np.load('./5_cmsis_mlp/model/dense_3_bias.npy')
weight = weight.astype(np.int64)
bias = bias.astype(np.int64)

input_zero_point = 128
multipler = 1863683814
shift = -9
output_zero_point = 21

correct = np.matmul(input_data + input_zero_point, weight.T) + bias
correct = correct * multipler / 2**(31 + (-shift))
correct += output_zero_point
correct = np.clip(correct, -128, 127).astype(np.int32)
print(correct)

stm32_val = np.matmul(input_data_stm32 + input_zero_point, weight.T) + bias
stm32_val = stm32_val * multipler / 2**(31 + (-shift))
stm32_val += output_zero_point
stm32_val = np.clip(stm32_val, -128, 127).astype(np.int32)
print(stm32_val)

[-13 -18  19  31 -44 -13 -44  77   7  12]
[-12 -18  18  31 -43 -12 -42  76   8  11]
