# 数据生成

该文本用于生成NN的一些测试数据，主要是python能够更方便生成重复数据

In [6]:
import numpy as np

## pooling

In [2]:
in_vec = [-1, 0, 1, 2, 2, 3, 5, 4, 7, 0, 0, 0, -1, -2, 0, 9]
in_vec = np.tile(in_vec, (2,1))
in_vec

array([[-1,  0,  1,  2,  2,  3,  5,  4,  7,  0,  0,  0, -1, -2,  0,  9],
       [-1,  0,  1,  2,  2,  3,  5,  4,  7,  0,  0,  0, -1, -2,  0,  9]])

In [3]:
in_vec = [-1, 0, 1, 2, 2, 3, 5, 4, 7, 0, 0, 0, -1, -2, 0, 9]
in_vec = np.repeat(in_vec, 2)
in_vec

array([-1, -1,  0,  0,  1,  1,  2,  2,  2,  2,  3,  3,  5,  5,  4,  4,  7,
        7,  0,  0,  0,  0,  0,  0, -1, -1, -2, -2,  0,  0,  9,  9])

## Conv

### 例1

In [22]:
in_vec_channel_1 = np.ones((16,), dtype=np.int32)
in_vec_channel_2 = in_vec_channel_1 * 2

print(in_vec_channel_1)
print(in_vec_channel_2)

# in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).reshape(-1)
in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).T.reshape(-1)
in_vec

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


array([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 2, 1, 2], dtype=int32)

In [23]:
weight_kernel_1_channel_1 = np.ones((3, 3), dtype=np.int32) * 2
weight_kernel_1_channel_2 = np.ones((3, 3), dtype=np.int32) * 3
weight_kernel_1 = np.array([weight_kernel_1_channel_1, weight_kernel_1_channel_2])
print(weight_kernel_1.shape)

weight_kernel_2_channel_1 = np.ones((3, 3), dtype=np.int32) * 3
weight_kernel_2_channel_2 = np.ones((3, 3), dtype=np.int32) * 1
weight_kernel_2 = np.array([weight_kernel_2_channel_1, weight_kernel_2_channel_2])
print(weight_kernel_2.shape)

weight = np.array([weight_kernel_1, weight_kernel_2]).transpose(1,2,3,0)
print(weight.shape)
weight = weight.reshape(-1)

# 生成所有权重相同的测试用
# weight = np.ones((36,), dtype=np.int)
weight

(2, 3, 3)
(2, 3, 3)
(2, 3, 3, 2)


array([2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1], dtype=int32)

### 例2

In [50]:
in_vec_channel_1 = np.concatenate((np.arange(1, 10, dtype=np.int32), np.arange(1, 8, dtype=np.int32)))
in_vec_channel_2 = np.ones((16,), dtype=np.int32)

print(in_vec_channel_1)
print(in_vec_channel_2)

# in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).reshape(-1)
in_vec = np.array([in_vec_channel_1, in_vec_channel_2]).T.reshape(-1)
in_vec

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


array([1, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9, 1, 1, 1, 2, 1,
       3, 1, 4, 1, 5, 1, 6, 1, 7, 1], dtype=int32)

In [62]:
weight_kernel_1_channel_1 = np.ones((3, 3), dtype=np.int32) * 2
weight_kernel_1_channel_2 = np.arange(1, 10, dtype=np.int32).reshape(3, 3) * -1
weight_kernel_1 = np.array([weight_kernel_1_channel_1, weight_kernel_1_channel_2])
weight_kernel_1 = weight_kernel_1.transpose(1,2,0)
print(weight_kernel_1.shape)

weight_kernel_2_channel_1 = np.array([1,2,3,1,2,3,1,2,3], dtype=np.int32).reshape(3, 3)
weight_kernel_2_channel_2 = np.ones((3, 3), dtype=np.int32)
weight_kernel_2 = np.array([weight_kernel_2_channel_1, weight_kernel_2_channel_2])
weight_kernel_2 = weight_kernel_2.transpose(1,2,0)
print(weight_kernel_2.shape)

weight = np.array([weight_kernel_1, weight_kernel_2])
print(weight.shape)
weight = weight.reshape(-1)

# 生成所有权重相同的测试用
# weight = np.ones((36,), dtype=np.int)
weight

(3, 3, 2)
(3, 3, 2)
(2, 3, 3, 2)


array([ 2, -1,  2, -2,  2, -3,  2, -4,  2, -5,  2, -6,  2, -7,  2, -8,  2,
       -9,  1,  1,  2,  1,  3,  1,  1,  1,  2,  1,  3,  1,  1,  1,  2,  1,
        3,  1], dtype=int32)

## Dense

In [73]:
in_vec = np.array([[-1, -2, 1, 2, 3]]).T
weight = np.array([[2, 1, 2, 2, 2], [2, 2, 1, 2, 2], [2, 2, 1, 1, 2]], dtype=np.int32)

print('correct answer')
print(np.matmul(weight, in_vec))

correct answer
[[8]
 [5]
 [3]]


In [74]:
in_vec.T

array([[-1, -2,  1,  2,  3]])

In [72]:
weight.reshape(-1)

array([2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2], dtype=int32)

# 正确的参考结果生成

In [1]:
import torch

## Conv

### 例2

In [59]:
# 构建输入
in_vec_channel_1 = np.concatenate((np.arange(1, 10, dtype=np.int32), np.arange(1, 8, dtype=np.int32))).reshape(4,4)
in_vec_channel_2 = np.ones((16,), dtype=np.int32).reshape(4,4)

in_vec = np.array([in_vec_channel_1, in_vec_channel_2])
in_vec = in_vec[np.newaxis, :]
print(in_vec.shape)
in_vec

(1, 2, 4, 4)


array([[[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 1, 2, 3],
         [4, 5, 6, 7]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]], dtype=int32)

In [60]:
# 构建权重
weight_kernel_1_channel_1 = np.ones((3, 3), dtype=np.int32) * 2
weight_kernel_1_channel_2 = np.arange(1, 10, dtype=np.int32).reshape(3, 3) * -1
weight_kernel_1 = np.array([weight_kernel_1_channel_1, weight_kernel_1_channel_2])
print(weight_kernel_1.shape)

weight_kernel_2_channel_1 = np.array([1,2,3,1,2,3,1,2,3], dtype=np.int32).reshape(3, 3)
weight_kernel_2_channel_2 = np.ones((3, 3), dtype=np.int32)
weight_kernel_2 = np.array([weight_kernel_2_channel_1, weight_kernel_2_channel_2])
print(weight_kernel_2.shape)

weight = np.array([weight_kernel_1, weight_kernel_2])
print(weight.shape)

# 生成所有权重相同的测试用
# weight = np.ones((36,), dtype=np.int)
weight

(2, 3, 3)
(2, 3, 3)
(2, 2, 3, 3)


array([[[[ 2,  2,  2],
         [ 2,  2,  2],
         [ 2,  2,  2]],

        [[-1, -2, -3],
         [-4, -5, -6],
         [-7, -8, -9]]],


       [[[ 1,  2,  3],
         [ 1,  2,  3],
         [ 1,  2,  3]],

        [[ 1,  1,  1],
         [ 1,  1,  1],
         [ 1,  1,  1]]]], dtype=int32)

In [61]:
in_vec = torch.Tensor(in_vec)
weight = torch.Tensor(weight)
output = torch.conv2d(in_vec, weight)

output

tensor([[[[ 27.,  27.],
          [ 45.,  45.]],

         [[ 78.,  87.],
          [ 96., 105.]]]])